### ISSUE TITLE
Singe camera results

### ISSUE THREAD

**Issue by xiaochehe** [sail-sg/mvp#16]
I have a question about your work. "Direct Multi-view Multi-person 3D Pose Estimation NIPS 2021". Your multiview performance on Panoptic Dataset is much better than VoxelPose. However, why aren't you as good as him with a single view setting. Your MPJPE is 93.8mm while VoxelPose's MPJPE is 66.95mm. And of course, I can't reproduce their results. Could you help me with this problem? Thx

**Comment by twangnh** [comment]
Thanks for your interest in our work. the performance is lower for the single view setting, this is mainly because voxelpose explicitly regresses the 3d coordinates with the voxel design, this introduces strong architectural prior so that it is advantageous when the depth ambiguity is severe (e.g., single view). Of course, we have not deliberately tried to tuning mvp for the single view setting, maybe it can be improved.

**Comment by xiaochehe** [comment]
https://github.com/karfly/learnable-triangulation-pytorch/issues/64#issue-588872398

For a voxelpose-based method in a single-view setup, they train their model on 1 – 4 views simultaneously.  Are you in a similar way?

**Comment by twangnh** [comment]
we used only single view training and test for the single-view setup

**Comment by xiaochehe** [comment]
get it, Thx
